import React from 'react';
import Head from "next/head";

const Button = () => {
    return (
        <div>
            <Head>
                <title>Button in tailwind</title>
                <meta name="desription" content="Generated by next app" />
                <link rel="icon" href="/favicon.ice" />
            </Head>

            <div className="flex justify-center itenms-center mt-48">
                <button>Style</button>
            </div>
        </div>
    );
};

export default Button;