import React from "react";
import Head from "next/head";

const Fsl = () => {
    return (
        <div>
            <Head>
                <title>Tailwind Buttons</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="Icon" href="/favicon/ico" />
            </Head>
            <div className="flex justifty-center mt-60">
                <h1 className="font-mono font-black text-8xl subpixel-antialiased w-4/5 tracking-normal text-slate-400">Font size and spacing</h1>
            </div>
        </div>
    );
};

export default Fsl;